name: "Run tests and coverage"

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-20.04, macOS-10.15, windows-2019]

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.11

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install .
        pip install .["dev"]

    - name: Test with pytest
      run: |
        coverage run -m pytest -v
        coverage report -m
        coverage xml

    - name: Upload coverage reports to Codecov
      uses: codecov/codecov-action@v3
      if: always()
      continue-on-error: true
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        file: coverage.xml
        flags: cpu,pytest,${{ runner.os }}
        name: Test-coverage
        fail_ci_if_error: false
